### ISSUE TITLE
"Shared VPCs" supported by VPC Access connector in Beta

### ISSUE THREAD

**Issue by archyufa** [ahmetb/cloud-run-faq#109]
Needs to update following information:
Are "Shared VPCs" supported by VPC Access connector?

from: Currently not
to: Yes, Currently in Beta

URL: https://github.com/ahmetb/cloud-run-faq#are-shared-vpcs-supported-by-vpc-access-connector

**Comment by ahmetb** [comment]
Seems already fixed, Thank you. 🙏
