### ISSUE TITLE
GAE Flexible supports Websockets in beta, unlike Cloud Run.

### ISSUE THREAD

**Issue by jmckevitt-oanda** [ahmetb/cloud-run-faq#120]
Hi, i see that cloud run now **supports** websockets 
https://github.com/ahmetb/cloud-run-faq#are-websockets-supported-on-cloud-run

So i think we should correct this point in the _How is it different than App Engine Flexible_ quesiton.

I was pleasantly surprised to read this later on in the readme.  

Great work on the readme btw.

**Comment by ahmetb** [comment]
Yeah just an oversight, sorry.
