### ISSUE TITLE
Reverse proxy setting Host header leads to 413 errors

### ISSUE THREAD

**Issue by mkhl** [ahmetb/cloud-run-faq#121]
Hi, not sure if this fits here but…
A while ago I was trying to run a reverse proxy for some application, both of which run on cloud run, with an nginx configuration like this:

	location / {
		proxy_pass …;
		proxy_set_header Host $http_host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Host $http_host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

All requests processes like this ended up generating (google-themed) 413 error responses, and the proxy had logged hundreds of requests for each request sent by the browser.
Funnily proxying to google.com instead of the application had the same result.

At some point I figured out that the `Host` header caused the problem, my guess would be that google's load balancers use it to choose where to route requests, but I hadn't seen this behavior documented.

(Aside: I had added the `Host` header directive since the other application I was proxying to, keycloak, seems to use that to determine which host the user agent had requested)

**Comment by ahmetb** [comment]
Can you please ask this on Stackoverflow.com?

**Comment by mkhl** [comment]
So I should ask this and answer this myself so I can point out a limitation that I think belongs in the actual documentation?

**Comment by ahmetb** [comment]
If you're behind a multi-tenant load balancer, it's very likely the  Host header is used to route the request. This doesn't need to be documented.

**Comment by tinsch** [comment]
But how do you know that you are behind a multi-tenant load balancer when you are using Cloud Run? Is it already documented somewhere?
