### ISSUE TITLE
Can different cloudrun instances of the same application talk to each other?

### ISSUE THREAD

**Issue by rusenask** [ahmetb/cloud-run-faq#122]
Let's say I create a cloudrun application and it scales to 2 containers. Is there some metadata env vars available like in k8s that would allow the container to determine its own IP address so that it could advertise it and let the other instance to connect to it?

**Comment by AniX** [comment]
If sync messages, why not just use the app's host URL?  For async I would recommend Pub/Sub (if you need throughput and speed) or Cloud Tasks (if you need control over rate limit). The documentation recommends that you avoid background processes, though.

**Comment by rusenask** [comment]
in my case I have some long lived connections opening and then some incoming requests need to be routed to the app instance that has the connection open from a device. It's mostly SSH tunnelling but building more on this functionality. 

In k8s what I would do:
1. Once a device connects to the server, I put the device ID and pod IP into Redis
2. Once user tries to connect to the device and if I know that the device is not connected to the current instance that has accepted the connection, do a TCP forwarding to another pod that I know has the connected device (retrieve that info from Redis)

Not sure how would this work in CloudRun. I suspect that they must have some internal IPs available. Otherwise I would need a separate deployment for these long lived connections from devices.

**Comment by ahmetb** [comment]
There's no individual addressing of containers on Cloud Run.
We also don't show you individual container instances.
