### ISSUE TITLE
Not sure if Cloud Run uses Let's Encrypt to provision a certificate

### ISSUE THREAD

**Issue by nelsonjchen** [ahmetb/cloud-run-faq#126]
https://github.com/ahmetb/cloud-run-faq#user-content-does-cloud-run-offer-ssltls-certificates-https:~:text=If%20you%E2%80%99re%20using%20your%20own%20custom,get%20a%20certificate%20for%20your%20domains.

My last Cloud Run project seems to have had its certificate issued by Google Trust Services and not out of the Let's Encrypt infrastructure:

https://github-wiki-see.mindflakes.com/

**Comment by ahmetb** [comment]
ack that changed at some point.
