### ISSUE TITLE
Problem with download file from external system

### ISSUE THREAD

**Issue by NothingCtrl** [ahmetb/cloud-run-faq#127]
My `flask` app run on Cloud Run but I have problem that `urlopen()` to download file from other service to serving user request is not working, request error with http status code `403`. I tested with many url but non woking.

Does Google Cloud Run is not allow application to download file from external services?

**Comment by ahmetb** [comment]
Cloud Run can connect to internet just fine. But  please ask this sort of questions on Stackoverflow.com.
