### ISSUE TITLE
Some feedback on billing

### ISSUE THREAD

**Issue by CatalinAdlerDF** [ahmetb/cloud-run-faq#129]
Hi, nice summary you have here.
Few things i've noticed:

1. Max timeout is more refined than 15 min. it's up to 1h on managed cloud run (though pre-ga for now) and i think up to 24h on anthos.
2. On billing you say `If your service handles multiple requests simultaneously, you do not pay for them separately` this is only partially correct. With concurrent requests you don't pay for additional cpu/ram, but you pay for each request individually.
3. A note that with anthos you don't pay per request might help showcase the best pricing model: cloudrun on gke on premptible might be the sweet-spot of computing today.

**Comment by ahmetb** [comment]
Thanks, I'll update.
