### ISSUE TITLE
Not sure if Cloud Run uses its own certificate authority to provision a certificate

### ISSUE THREAD

**Issue by nelsonjchen** [ahmetb/cloud-run-faq#131]
In https://github.com/ahmetb/cloud-run-faq/issues/126, I was uncertain if certificates were generated by Let's Encrypt. 

At least for this `.page` domain, it uses Let's Encrypt. 

https://github-wiki-see.page/

Does Cloud Run use a different CA for different TLDs? Or does it use its own CA for subdomains of verified properties?

**Comment by ahmetb** [comment]
I'm not entirely sure. I don't think it's per-TLD, but rather a function of time. Maybe older domain mappings use LE but newer ones use GTS. Can’t give a certain answer.

**Comment by nelsonjchen** [comment]
I just made that domain mapping an hour ago.

**Comment by ahmetb** [comment]
Could be a regional thing or another experiment going on.
