### ISSUE TITLE
Offer extended commentary on keeping services hot

### ISSUE THREAD

**Issue by atrauzzi** [ahmetb/cloud-run-faq#135]
In the section about [keeping cloud run services warm](https://github.com/ahmetb/cloud-run-faq#how-to-keep-a-cloud-run-service-warm), the following is suggested:

> You can also work around "cold starts" by periodically making requests to your Cloud Run service which can help prevent the container instances from scaling to zero. For this, use Google Cloud Scheduler to make requests every few minutes.

I'm okay with this idea, but what I'm interested in hearing are some general thoughts around a few topics when using Cloud Scheduler to keep a Google Cloud Run service hot:

  - What are reasonable expectations in terms of performance?
  - Does Cloud Run have any (subtle?) behaviours that might impact the reliability and uptime of a service that has been bodged into staying up 24/7?
  - Would Google view this as an exception to normal use?
  - How does the value proposition of an always-hot Google Cloud Run service contrast to say... App Engine Flexible? Is it totally eroded, or is the pricing model around Google Cloud Run equal to or still under App Engine, even if hot 24/7? For example, is someone keeping a Cloud Run service hot likely to pay more, the same or less than someone who runs the same application on App Engine?

I think you get the overall idea here, some forward thinking commentary on likely gotchas might help people who are evaluating Cloud Run for latency-sensitive services.

Even if keeping a Cloud Run service warm means paying more than a service that's allowed to go dormant, if that amount is still comparable to any other always-on PaaS right now, Cloud Run's other features and abstractions are attractive enough to justify configuring a measly Cloud Scheduler.

**But only if that's the only compromise!** :wink:

**Comment by ahmetb** [comment]
Sorry but this repo is not the forum to discuss this and I can't answer these either.

Feel free to report this to our public issue tracker.

**Comment by atrauzzi** [comment]
Hm, dang.  I was hoping there would be some conventional wisdom around this, nothing too detailed.  But just enough to help people out.
