### ISSUE TITLE
minInstance doesn't work

### ISSUE THREAD

**Issue by TonyChiangUSA** [ahmetb/cloud-run-faq#152]
It's a very simple API App, insert data to BigQuery but you can see the requests latency, 99% of them cost around 4s which is totally unacceptable for our website. I've set minInstance to 1 to avoid cold start and every isntance is 1vcpu and 521M. What can i do to improve the latency?

![image](https://user-images.githubusercontent.com/6076463/127827703-9ea7b3bd-b441-40e6-9601-78a950df460e.png)

**Comment by ahmetb** [comment]
￼please submit feedback through google cloud's public issue tracker.
