### ISSUE TITLE
Does GCP charges for cold start time?

### ISSUE THREAD

**Issue by gold-ly** [ahmetb/cloud-run-faq#154]
I was wondering if GCP charges for the time the container is cold starting.

**Comment by ahmetb** [comment]
That's a good question.

You're not charged during the duration while the infrastructure is getting warmed up.

But you are charged while your container is started (and not yet listening on the port number). So if your app is slow to start the HTTP server, you're actually charged for that period. 


This is actually clear in the docs (https://cloud.google.com/run/pricing): 

![image](https://user-images.githubusercontent.com/159209/129240245-0e9c0a07-631c-4cc6-a12f-98aa836be007.png)

**Comment by gold-ly** [comment]
Thanks for the fast answer, Ahmet!
