### ISSUE TITLE
Question about http requests through vpc connector

### ISSUE THREAD

**Issue by fmmoret** [ahmetb/cloud-run-faq#163]
If I make a plain (unencrypted) network request to `http://<some vpc network address>/...` is the request encrypted between my cloud run instance and the VPC connector? For the leg of the trip once it's in my vpc, I expect it to be plain http. 

And for responses routed back to my cloud run instance, are those response packets encrypted between my vpc connector and my cloud run instance?

I fully expect everything to be unencrypted inside my vpc but I'd like to understand that small gap between my CR instances and the connector. I wouldn't be surprised if you all are wrapping my request in your own encrypted request and then unwrapping on the connector to forward to the VPC.

More color on precisely how the VPC connector communication works in cloud run could be useful.

**Comment by ahmetb** [comment]
Inside Google's datacenters, all data in transit is encrypted. You can learn more here https://cloud.google.com/security/encryption-in-transit/.
