### ISSUE TITLE
Question: Can I force each request to run in its own container?

### ISSUE THREAD

**Issue by oyvindsk** [ahmetb/cloud-run-faq#24]
Without running Docker In Docker? Maybe by setting "concurrency" to 1 and stopping my container after handling 1 http request? 

Anyone tried that? :D

The usecase is  that I have a case that needs more "sandboxing" than usual, and running each http request in its own container seems useful (but slow, of course).

**Comment by ahmetb** [comment]
It looks like you don't want to reuse containers. This is not a common use case, so I won't add  to faq.

But as you said, if you use --concurrency=1, and exit from the container (like, crash the container) after the request, you'll get a new container.

**Comment by oyvindsk** [comment]
Yeah, understandable. It's probably not very common :) 

Unsure if it's even possible to do what I want. If I was Google I might try to reuse the container somehow, even after it "exited". 

(Also, for the record, even creating a new docker container for each request might not be good enough for security reasons. Google probably use gVisor, which *is* good enough for my case, but it's hard to know what's actually happening in Cloud Run)
