### ISSUE TITLE
Question: Is GCP IAP supported? Or support planned?

### ISSUE THREAD

**Issue by sitepodmatt** [ahmetb/cloud-run-faq#26]
Question: Is GCP IAP supported? Or support planned?

**Comment by sneko** [comment]
Hi,

I'm also interested in.

As mentioned here (https://stackoverflow.com/a/56081928):
`In the future, it's likely we'll offer IAP (which hosts an OAuth client for you).`

Any news since then @ahmetb ?

Thank you,

**Comment by ahmetb** [comment]
Can’t share product timelines here, but it’s soon.
