### ISSUE TITLE
Question: What happens when concurrency is set to 0?

### ISSUE THREAD

**Issue by ahmetb** [ahmetb/cloud-run-faq#27]
cc: @steren per twitter thread. 
I think we should have this behavior documented, especially if there's magic around it rather than just being unbounded  concurrency.

**Comment by steren** [comment]
Documented yes, but here is not the place to start with.
https://cloud.google.com/run/docs/about-concurrency is the page to improve,

**Comment by ahmetb** [comment]
Looks like API supports `containerConcurrency: 0` but defaults to `80`. `gcloud` CLI rejects this. So probably not worth documenting here.
