### ISSUE TITLE
Question: Can I mount volumes to Cloud Run?

### ISSUE THREAD

**Issue by dbporto** [ahmetb/cloud-run-faq#28]
Some of my applications need to store configuration files on volumes inside the cluster (the Grafana container, for example) and I sometimes use volumes to store service accounts (Pub/Sub publisher and reader, storage owned and so on). I do that by configuring my volumeMounts and volumes on my deployment.yaml.

**Comment by ahmetb** [comment]
Today, the answer depends on whether you’re using Cloud Run –OR– Cloud Run on GKE.
Which one are you using?

**Comment by dbporto** [comment]
Hi ahmetb, thanks for answering.

Currently we are trying with Cloud Run on GKE.

Our plan is to use Cloud Run to autoscale some of our APIs that have high usage during the day and 0 at night.

**Comment by ahmetb** [comment]
The answer would be yes on GKE. It appears like this is not documented very well, so I'm raising a ticket to Knative documentation (https://github.com/knative/docs/issues/1413) and we'll be looking at documenting this on Cloud Run website as well.

If you’re writing YAML manifests as you said, take a look at [Knative Secrets](https://knative.dev/docs/serving/samples/secrets-go/index.html) sample which uses `volumes` & `volumeMounts` fields, just like in Kubernetes. Any valid Kubernetes volume spec that works in your cluster should be also working on your Knative Service spec.
