### ISSUE TITLE
Question: Can I use a reserved public ip address to egress traffic?

### ISSUE THREAD

**Issue by aaaguirrep** [ahmetb/cloud-run-faq#30]
Hi, 

At present I have a service in google cloud run that connected to others REST API/services to retrieve specific information. The other services need whitelist the public/external ip address from the source service (Google Cloud Run).

Can I assign a reserved public/external ip address from Google Cloud Networking to my Google Cloud Run service?

Regards,
Arsenio

**Comment by ahmetb** [comment]
This is currently not possible. However, you can probably host a SOCKS proxy somewhere (like a GCE instance with a static IP) and set your app to proxy particular connections through that.

I'll probably create a Networking section and add this there.

**Comment by aaaguirrep** [comment]
Thanks, Networking section sounds good.

In the meantime I will check how to do it.

**Comment by ahmetb** [comment]
Already documented at https://github.com/ahmetb/cloud-run-faq#is-there-a-way-to-get-static-ip-for-outbound-requests, forgot to close.
