### ISSUE TITLE
Question: Does Cloud Run have health checks?

### ISSUE THREAD

**Issue by apstndb** [ahmetb/cloud-run-faq#31]
`How can I serve traffic multiple revisions?` is written as below.
>However, Cloud Run (currently) only supports serving traffic from the last healthy revision of your service. Therefore, it currently does not support revision based traffic splitting and canary deployments.

There is no description of `healthy revision` in Cloud Run FAQ.
I think that it is defined as [Listening for requests on PORT](https://cloud.google.com/run/docs/reference/container-contract?hl=en#port) in Cloud Run's container runtime contract and Cloud Run doesn't have L7 health checks.
>The container must listen for requests on 0.0.0.0 on the port defined by the PORT environment variable.

[Meta Requests](https://github.com/knative/serving/blob/master/docs/runtime-contract.md#deployment-probe) of Knative's container runtime contract has more description but I am not sure that Cloud Run does support deploymentProbe/livenessProbe setting in REST API.

refs: https://cloud.google.com/run/docs/troubleshooting?hl=en

**Comment by ahmetb** [comment]
I think this is a fair question. Thanks for bringing  up.

How Knative does health checks vs how Cloud Run hosted version does health checks are pretty different. I'll inquire what we can explain in this repo and in the docs.

**Comment by boredland** [comment]
That is very sad. So health/readiness is only determined by "listening to Port" and cant be configured to actually containing a certain string or sth.

**Comment by javapapo** [comment]
@ahmetb This particular question / tip I think its worth beeing added to the main FAQ?

**Comment by ahmetb** [comment]
Fixed in dda1899.

**Comment by steren** [comment]
Cloud Run now supports health checks: https://cloud.google.com/run/docs/configuring/healthchecks
