### ISSUE TITLE
Does Cloud Run timeout apply on GKE-Cluster?

### ISSUE THREAD

**Issue by daudn** [ahmetb/cloud-run-faq#32]
Does Cloud Run timeout apply on GKE-Cluster? If it does, will it always apply, or is this being looked in to?

**Comment by ahmetb** [comment]
Currently it's 10 minutes. We'll take a look at documenting it as soon as possible. Maybe then I can comment on whether we're planning to change it.

**Comment by ahmetb** [comment]
This is documented in the docs, so won't re-document here.
https://cloud.google.com/run/quotas
