### ISSUE TITLE
Best practices for scale to zero and cold start

### ISSUE THREAD

**Issue by maestrofx** [ahmetb/cloud-run-faq#34]
Hi,
I have several questions to understand **scale to zero**.

- How to approach best practices for **cold start**?
- If no traffic, does it kill the container, and spin up the new one if it's needed? 
- How long the container up and running before it's stated idle and scale to zero? And how do I know this container is scaled to zero?

Thanks

**Comment by maestrofx** [comment]
I am just thinking which use cases I want to move to Cloud Run or Cloud Run for GKE.
This is interesting for my case, for the first choice I will use Cloud Run such as micro batch, log collector. But the needs for inter-communication among the services, connecting to VPC, it's like Cloud Run for GKE is the great choice.

Just exploring for case by case right now. :)

**Comment by dikatok** [comment]
Hi, I am also in preparation to use Cloud Run in my current project. As stated in the repo, you can ping the service periodically, eg: using scheduler + cloud functions to call one of the endpoints (/warm perhaps) to keep at least 1 container running. I have not used it yet, but I think it will work.

**Comment by jeremyjensen3** [comment]
My company has a Cloud Run service running in Production now and so I have some info to offer here. We have seen our Cloud Run containers scale down to zero in as little as 2 minutes of inactivity. To remedy this we setup Stackdriver Uptime Checks which are free to use as far as I know and can be configured to send requests to your service up to 6 x times a minute if you use all available regions, more than enough to keep the container active. You get the added benefit of an external health check for your service too.

**Comment by ahmetb** [comment]
I won't document best practices here but https://cloud.google.com/run/docs/tips might help with some of these. It's hard to comment on stuff around cold start, as it does not have a predictable model and depends on available infra capacity etc. Thanks for the discussion above, it helps us document what else people might be wondering about.
