### ISSUE TITLE
How do two Cloud Run containerized apps communicate with each other?

### ISSUE THREAD

**Issue by ndtreviv** [ahmetb/cloud-run-faq#37]
This describes the question: https://stackoverflow.com/questions/57689876/google-cloud-run-container-networking

**Comment by coffenbacher** [comment]
I'm still experimenting with this myself but I feel like Pulumi might be a good option here. I think you might be able to use it to script the creation of the Cloud Run endpoints, and reference each other that way.

**Comment by javapapo** [comment]
I had this question as well I think is a good candidate to be documented on the FAW (cc @ahmetb) especially his Stackoverflow answer

```

Cloud Run currently does not support hostname based service discovery for other services in your project.

Currently, your best bet is to configure service URLs that your app depends on using environment variables or something like that.
```

**Comment by ahmetb** [comment]
Yeah good point.
FWIW we're working on this, stay tuned.

**Comment by ahmetb** [comment]
Fixed in master, see `Microservices` heading.
