### ISSUE TITLE
Are user sessions routed to the same instance once a service has been scaled?

### ISSUE THREAD

**Issue by ndtreviv** [ahmetb/cloud-run-faq#38]
For example,

If my app has OAuth 2.0 + PKCE authorization code flow against a third party identity provider, can I guarantee that after the user has logged in on the third party's site and is redirected back they are redirected back to the same instance?

If they are not, the new instance they are redirected back to will know nothing about the code_verifier.

**Comment by ahmetb** [comment]
Good question. 
No, the session stickiness is not guaranteed at all. You should use an external state storage for stuff like auth flows, sessions etc.

**Comment by ndtreviv** [comment]
Got an example in node.js using passport-oauth2 perchance?! 😉

**Comment by ahmetb** [comment]
I don't know anything about Node.js but its source code has SessionStateStore which is clearly what you're looking for. Maybe there's a redis implementation of SessionStateStore that you can use with Cloud Memorystore or something like that.

**Comment by ahmetb** [comment]
Closing since this is already answered at https://github.com/ahmetb/cloud-run-faq#can-i-make-request-to-a-specific-container-instance
