### ISSUE TITLE
Question: Mapping Cloud Run Services Domain to a Wildcard Domain

### ISSUE THREAD

**Issue by Timtech4u** [ahmetb/cloud-run-faq#39]
Hi @ahmetb @steren ,

I have an actual domain but would like to map individual Cloud Run Services to a wildcard e.g. *.mydomain.com (so that I don't have to add individual records for each Cloud Run Service)

I am a bit confused as at why this is not working fine as I have added the correct DNS records.

**Comment by ahmetb** [comment]
I don’t think wildcard records are supported on Cloud Run (fully managed). As far as I know you need to create mapping for each domain. 
 But they work on Cloud Run on GKE for sure.

**Comment by Timtech4u** [comment]
Thanks @ahmetb ,  I'll make use DNS records that map each sub-domain to each of my Cloud Run Service.

However, recently, it's taking really forever to get domains map.

![Screenshot from 2019-09-03 12-12-42](https://user-images.githubusercontent.com/11256481/64168810-45767580-ce44-11e9-9c3f-841ba87061a4.png)
I have added the DNS Records already and verified the base domain, but it takes too long to map.

**Comment by Timtech4u** [comment]
Hi @ahmetb , do also checkout https://issuetracker.google.com/issues/140398822

**Comment by ahmetb** [comment]
Not being able to create wildcard records in Cloud Run is a valid feature request. Feel free to push it in the same bug tracker.

Regarding your other issue, you already posted it to the issue tracker, thanks for that. There's not much I can do. Looks like folks are already taking a look.

**Comment by Timtech4u** [comment]
Thank you, hope this gets resolved ASAP :)

**Comment by acazacu** [comment]
@Timtech4u Are you using Cloud Run or Cloud for Anthos? You can use wildcard domains on Cloud Run for Anthos by setting your GKE cluster's default domain. From there on, any publicly available run that you deploy will be assigned a url in the following format:

`https://[cloud-run-service-name].[cloud-run-service-namespace].your-domain.com`

**Comment by Timtech4u** [comment]
> @Timtech4u Are you using Cloud Run or Cloud for Anthos? You can use wildcard domains on Cloud Run for Anthos by setting your GKE cluster's default domain. From there on, any publicly available run that you deploy will be assigned a url in the following format:
> 
> `https://[cloud-run-service-name].[cloud-run-service-namespace].your-domain.com`

Thanks for this @acazacu , my team and I are considering CR for Anthos.
