### ISSUE TITLE
Question: What happens when I exhaust the Let's encrypt rate limit?

### ISSUE THREAD

**Issue by Timtech4u** [ahmetb/cloud-run-faq#40]
My domains seem to now take forever to map, I tried using a VM Instance and setup SSL but Let's Encrypt tells me I have used up my rate limit which I believe is from my Cloud Run domain mappings.
 Is there an option when this happens?

**Comment by ahmetb** [comment]
I suspect not. You can't tell Let's Encrypt to reset the rate limit.
Did you try to get SSL yourself or did Cloud Run exhaust your rate limit?
I believe we have an existing issue in the Public Issue Tracker about the certs taking too long/forever to set up?

**Comment by Timtech4u** [comment]
Thanks for responding @ahmetb, I can guess Cloud Run exhausted the limit since I tried moving to a Compute Engine VM and provision SSL using Let's Encrypt but got the following error:
![Screenshot from 2019-09-10 07-56-53](https://user-images.githubusercontent.com/11256481/64646401-f1086280-d40e-11e9-8338-277a9746b74b.png)

I have a long list of domain mappings for Cloud Run that is still pending, here's few with some over 1day
![Screenshot from 2019-09-10 21-05-48](https://user-images.githubusercontent.com/11256481/64646458-0bdad700-d40f-11e9-8a4b-e6acf3089ec7.png)

I wouldn't mind doing a Reverse Proxy to the actual service URL gotten from Cloud Run, however I need to be able to provision SSL too, so if someone tries `test.mercuriemart.com` it proxy passes to the actual Cloud Run URL even if domain mapping fails for now.

**Comment by ahmetb** [comment]
We're investigating but it seems like you have a single quota (on Let's Encrypt side) for `mercuriemart.com`.

Can you answer these:
- how many subdomains you've added (and planning to add)
- how quickly did you add these subdomains (like: all on the same day, or N domains a day?)

**Comment by ahmetb** [comment]
> Personally, what do you think as a feasible approach for us?

Given your scale I would recommend creating a dedicated app (or an external proxy like Cloudflare) to handle your per-subdomain traffic and proxy it to their corresponding *.run.app endpoints.

You can also have something like:
- a main ("proxy") app that does proxying based on Host header (all your subdomain traffic goes over this)
- create CNAME records for all your subdomains (or 1 wildcard DNS record) that points to the "proxy" app
- get a wildcard CA certificate and configure it on your "proxy" app

I assume that's how `*.wordpress.com` does this.

**Comment by steren** [comment]
The limits have now been captured in the official Cloud Run quota page: https://cloud.google.com/run/quotas

**Comment by Timtech4u** [comment]
Thanks for the details, I have also been following up with the responses on the [issue](https://issuetracker.google.com/issues/140398822).

I temporarily resolved into using a Nginx deployment as my Reverse Proxy Server with Dynamic Configuration files for different sub-domains that proxies to Cloud Run *.run.app domain.

Looking forward to exploring more of Cloud Run and giving feedbacks. :+1:

**Comment by ahmetb** [comment]
This probably should no longer be the case as Google now uses its own CA for provisioning certificates for custom domains. e.g.

![image](https://user-images.githubusercontent.com/159209/80629960-6067ac80-8a08-11ea-9e5c-f93bd8c19249.png)

**Comment by scr4bble** [comment]
Yes, it seems like they use their own CA now but the limit is still there, am I correct?
Could you maybe update FAQ if the way of generating certs via letsencrypt is no longer valid?
Do you know if they plan to remove the limit for number of issued certificates (number of added custom domains)?
