### ISSUE TITLE
Cold start took 40 seconds 

### ISSUE THREAD

**Issue by yuya-kanai** [ahmetb/cloud-run-faq#45]
> Cold start latency depends on many factors, however many users observe additional ~2 seconds latency on cold starts. [more user data needed!]

I just want to inform that with my container, which was 1.13GB, I experienced a cold start time of **40 seconds**. The image was slimmed down with docker-slim and was hosted at the same region as the cloud run server.

**Comment by ahmetb** [comment]
I am hoping to run some tests to see if image size impacts cold starts or deployment times. 
Perhaps the first container instance is impacted but the rest doesn’t. I am not entirely sure. If you can

**Comment by manwithsteelnerves** [comment]
> I am hoping to run some tests to see if image size impacts cold starts or deployment times.

As per the docs, container size is not an overload for cold start.
