### ISSUE TITLE
document option of using Firebase with Cloud Run

### ISSUE THREAD

**Issue by naartjie** [ahmetb/cloud-run-faq#47]
This is Beta, but it looks like you can serve dynamic content via Firebase Hosting -> Cloud Run:

https://firebase.google.com/docs/hosting/cloud-run#direct_requests_to_container

It might be a good alternative since Cloud Run doesn't work with HTTP(S) Load Balancer.

**Comment by ahmetb** [comment]
It's already documented there? :)
