### ISSUE TITLE
When will VPC Connector come to Cloud Run?

### ISSUE THREAD

**Issue by luqmanhakim** [ahmetb/cloud-run-faq#56]
Hi Ahmet, any idea when this feature will arrive (if at all?). We're managing our own database that whitelists IP address for obvious security purposes. I read the workaround, but the solution still feels hack-ish.

So, any idea if any official static ip will come by to Cloud Run? My alternative is to just host the docker instance in an instance group with static ip. Let me know if you think there's a better way. Thanks!

**Comment by ahmetb** [comment]
It’s a top priority, so, soon. :)
Cannot share timelines in public forums or users not under NDA. I’ll make sure to announce it here and on twitter when it’s there.

**Comment by oitozero** [comment]
@ahmetb Any update on this?

**Comment by ahmetb** [comment]
We don’t share product timelines in this repo, sorry.

**Comment by ahmetb** [comment]
Hi folks, we have just announced VPC Connector support in beta.
You can find more at https://github.com/ahmetb/cloud-run-faq#vpc-support

**Comment by ahmetb** [comment]
@luqmanhakim We've also now launched the static IP feature:
https://twitter.com/ahmetb/status/1316157826486595584?s=20
Relevant section in FAQ: https://github.com/ahmetb/cloud-run-faq#is-there-a-way-to-get-static-ip-for-outbound-requests
