### ISSUE TITLE
Cloud run with database migrations

### ISSUE THREAD

**Issue by EamonKeane** [ahmetb/cloud-run-faq#58]
I would like to run db migrations in cloud run entrypoint to avoid having to use an external tool run this before promoting a revision.

In kubernetes this functionality can be achieved by having an init container on the deployment and setting max surge to 1, ensuring only one pod attempts the migration before rolling out to other containers.

Is the rollout strategy of CloudRun defined anywhere? It would be nice if CloudRun waited for one container in a revision to be healthy before cutting over wholesale, which would achieve this purpose.

**Comment by ahmetb** [comment]
Cloud Run offers traffic splitting. You can choose to send no (0%) traffic to a new revision at deployment time, and you can slowly roll out.

I am personally not familiar with how people do database migrations out there. But given your Kubernetes-oriented description, you won't have init containers, and currently you need to roll out the new version by setting the traffic percentage to the new Revision manually.

Hope this helps.

**Comment by ahmetb** [comment]
Answered on stackoverflow as well. Closing here.

**Comment by EamonKeane** [comment]
thanks @ahmetb
