### ISSUE TITLE
Is it possible to limit external access ?

### ISSUE THREAD

**Issue by mediarl** [ahmetb/cloud-run-faq#59]
Hi,

Is there a way to create a security group to limit access to the container's network?

I would like to execute user-generated code and thus avoid serving as a proxy for any kind of abuse or attack.

Is there a kind of security group feature somewhere that will allow to apply network rules on my container ?

Thanks

**Comment by ahmetb** [comment]
Google Cloud doesn't have the notion of "security groups".
But it uses IAM to restrict access to certain users or groups.
Read https://cloud.google.com/run/docs/authenticating/overview.
