### ISSUE TITLE
How can I get the current number of running instances?

### ISSUE THREAD

**Issue by yfuruyama** [ahmetb/cloud-run-faq#6]
As there is [upper limit](https://github.com/ahmetb/cloud-run-faq/blob/master/README.md#whats-the-upper-scaling-limit-for-cloud-run) of running instances, it’s great if we could know the current number.

**Comment by ahmetb** [comment]
Great question! This section talks about it

> ### Does my Cloud Run service scale to zero?
> 
> Yes, although you can’t really see how many container instances are running your service. [...]

but this question deserves a to be answered separately.

**Comment by ahmetb** [comment]
See #7.

**Comment by yfuruyama** [comment]
Great! Thank you so much for the clarification!
