### ISSUE TITLE
Question: What are some best practices for containerising functions for Cloud Run?

### ISSUE THREAD

**Issue by stxxart** [ahmetb/cloud-run-faq#63]
Hi @ahmetb,

I've got my own thoughts about this but I thought I'd get some second opinions about what is ideally containerised and deployed to Cloud Run. We currently have a large REST API, which is composed of numerous Lambdas / Cloud Functions. We want to move all our functions to Docker containers, as we don't like the _vendor lock-in_ and have a need to use _custom runtimes_.

The question we're still deliberating over is whether it's good practice to package a single function inside one container, or to combine multiple functions (within the scope of their microservice) into one container. In other words, keeping the granularity of services at the function level, or packaging all related functions as a group of routes (for example, Express).

I understand this question does not apply solely to Cloud Run, but we've obviously considered things like cold starts, minimal dependencies, global variables, image sizes, and the maximum service quota for Cloud Run.

If what I've mentioned doesn't really make a difference at scale, and is really just an architectural decision, I'd be happy to know.

Cheers!

**Comment by ahmetb** [comment]
Check out https://cloud.google.com/functions/docs/functions-framework.
Functions area is still very much a work-in-progress for open source Knative project as well and there are new proposals being discussed in those communities as I write this.
Whatever you find suits your needs is the best solution, as always. :)

**Comment by stxxart** [comment]
Thanks!!
