### ISSUE TITLE
Question: Why do I see POST requests every few milliseconds in the revision's logs?

### ISSUE THREAD

**Issue by EeveeWhitefire** [ahmetb/cloud-run-faq#64]
So I've made a cloud run revision that is executed when there's a new notification (OBJECT_FINALIZE) from a specific bucket (pubsub).
However, when I get in the revision's logs, every few seconds I see a new POST request even though no new objects were created/overwritten in that bucket.
[https://i.imgur.com/ZreOtKd.png](url)

And when there is a new object => I see that my code is executed like 5 times at the same time. Why is that?
[https://i.imgur.com/SoL9JfT.png](url)

I checked the output of `gsutil notification list` for the bucket (there is only one notification), and i have checked `gcloud pubsub subscriptions list` (there is only one subscription).
So what is causing this? I am honestly lost and annoyed because my code executes INSERT queries to the database and having duplicate values is silly...

If this is a result of the upscaling, then why does it upscale? I only tried having one request, this shouldn't cause my instance to create more instances... 
CPU allocation is 2, fully managed, 512MiB memory
Max instances and concurrency settings are default

**Comment by ahmetb** [comment]
I highly suspect this is a frequently asked question. 😊 Can you please ask on stackoverflow.com?
