### ISSUE TITLE
Tracing through a Cloud Run instance?

### ISSUE THREAD

**Issue by patrickbeekman** [ahmetb/cloud-run-faq#66]
I saw in the documentation that there was a [TODO section for Tracing](https://github.com/ahmetb/cloud-run-faq#how-can-i-do-tracing-on-cloud-run). Has anyone figured out how to do this? I have created a Flask app and run it using gunicorn inside a docker container. I have added tracing for the flask application. I can run the container locally and ping the endpoints, they show up in Trace. The problem arises when I deploy to Cloud run, if I ping the endpoints there then I do not see the Traces appear.

I am curious as to if anyone here has got Tracing working within Cloud Run?

**Comment by RomeroDiver** [comment]
Why did you close this? :( I came here with the similar question - does the Tracing work for Cloud run?
