### ISSUE TITLE
Question: Does Cloud Run support HTML5 SSE, Web Push API

### ISSUE THREAD

**Issue by DanielAsher** [ahmetb/cloud-run-faq#67]
I understand that Cloud Run does not support Web Sockets, which makes it unusable for my application. But I could rearchitect using HTTP Server Sent Events or perhaps the Web Push API.

I have found some information on the GCP slack channel indicating Web Push API would be supported, but I was unable to find any information on whether Cloud Run SSE or any other push technologies are supported. Including them here would be awesome!

**Comment by ahmetb** [comment]
SSE/gRPC server streaming is on the roadmap and is coming soon.
