### ISSUE TITLE
Can I make a restriction like credentials of API & Services in Google Cloud Platform?

### ISSUE THREAD

**Issue by JeongJun-Lee** [ahmetb/cloud-run-faq#68]
I want to make my own API server from docker, but the user who can use this API server should be restricted by some conditions. For example, by specific URL referrer, by specific Android App and by specific iOS App like image below.

![image](https://user-images.githubusercontent.com/11474775/76322721-8f657a00-6305-11ea-8a5e-bdc5db4415a3.png)

**Comment by lfx** [comment]
Hey, I think GCP Load Balancer is a way to go in your case https://cloud.google.com/load-balancing/docs/https

**Comment by JeongJun-Lee** [comment]
@lfx Thank you for your reply. But can I filter the specific iOS and Android App by GCP Load Banlancer?

**Comment by ahmetb** [comment]
@JeongJun-Lee currently you're looking for integration with Google Cloud Load Balancer or Cloud Endpoints or some API gateway product integration with Cloud Run, which does not exist. But it's on the roadmap, stay tuned!
