### ISSUE TITLE
How to send image file for processing in Cloud Run from iOS app

### ISSUE THREAD

**Issue by malemo** [ahmetb/cloud-run-faq#69]
I'm developing an image processing app for iOS and would like to keep the actual processing algorithm in the cloud. Based on my research Cloud Run looks like a perfect prospect. 

I need to be able to send an image file from iOS app to Cloud Run container. Container should process the image and return processed image. I don't need to store the processed and the original image in the cloud. 

I would really appreciate if somebody can clear up the below:

1. Is it possible to do this with just Cloud Run or I have to store the image in the Cloud storage?
2. How to send image file as a parameter to Cloud Run function and how to return processed image back to swift.
3. Do I have to use Vapor, Perfect or similar framework? If yes which is better?
4. The processing algorithm is divided into two parts: 
**Part1:** Image Segmentation written in python/pytorch, requires cuda/gpu support.
**Part2:** Image Processing written in Swift5
Do I need to have two separate containers for different codes? How would they communicate with each other?

Thank you.

**Comment by ahmetb** [comment]
As you might imagine your question is basically a consultation. If you have a specific question that looks like one of the questions in the homepage, I'm happy to answer.

Otherwise please ask for advice on Stackoverflow or GCP Community Slack channels.
