### ISSUE TITLE
What is equivalent of "X-Forwarded-For" in GRPC on Cloud Run?

### ISSUE THREAD

**Issue by rajveermalviya** [ahmetb/cloud-run-faq#71]
How to get client IP when using GRPC?

For example :
"X-Forwarded-For" header can be read to get client IP when using HTTP, Cloud Run HTTP proxy injects it.

**Comment by ahmetb** [comment]
It’s the same. Grpc is still http/2. But calls headers “metadata”.

**Comment by agmontpetit** [comment]
Do you know if there are any equivalent headers to [GAE headers](https://cloud.google.com/appengine/docs/flexible/python/reference/request-headers#app_engine-specific_headers) such as `X-AppEngine-Country`, `X-AppEngine-Region` or `X-AppEngine-City`?

**Comment by rajveermalviya** [comment]
From what I have tested it only injects (currently) these `X-` prefixed Headers :
`X-Cloud-Trace-Context`
`X-Forwarded-For`
`X-Forwarded-Proto`
