### ISSUE TITLE
Does cloud run support sending http/2 requests to my server(I know client can send http/2)

### ISSUE THREAD

**Issue by deanorderly** [ahmetb/cloud-run-faq#72]
Http/2 clients can send http2 to the google frontend which translates to http1.1 requests to my stateless server over http with special header.  How can I tell google to send my server http2 requests instead?

thanks,
Dean

**Comment by ahmetb** [comment]
Hi, I haven't fully understood the question. I'm assuming that you are referring to terms:
- "client" meaning an end-user's browser
- "server" meaning your container on Cloud Run. 

Normally, http/2 requires HTTPS. However, your container on Cloud Run (by the nature of container contract) needs to listen on HTTP (that said your traffic actually is still encrypted inside Google datacenters).

While your app is listening on unencrypted http, you need to implement a http2 listener that supports h2c (http2 unencrypted). For example, that's how gRPC works today on Cloud Run. gRPC, if no tls keys are configured, will listen on http2 but unencrypted.

So h2c must actually be working right now. Just make sure your app is supporting it. Also consider asking questions on https://stackoverflow.com/questions/tagged/google-cloud-run in the future. :)

**Comment by deanorderly** [comment]
hmmm, I thought this server did support h2 over the plain port.  I will
have to double check and fix if that is not the case.  thanks!!!!

Do you know if http1.1 comes into google, it will do http1.1 to server or
will it switch to http2?  (I guess I can test that with an http1.1 client
though now that I think about it).

This would be sick if I could cut the http1.1 stack out of the server and
reduce class count for startup.

thanks,
Dean

**Comment by ahmetb** [comment]
Hi Dean. I've answered it at https://stackoverflow.com/questions/61231930/can-i-have-my-cloudrun-server-receive-http-2-requests as well. I'll lock this discussion, let's move to there.

**Comment by ahmetb** [comment]
Documented in d99ef78.
