### ISSUE TITLE
Question: Costs for downloading items from cloud storage?

### ISSUE THREAD

**Issue by Tobjoern** [ahmetb/cloud-run-faq#73]
The [information on network pricing](https://cloud.google.com/network-tiers/pricing) suggests, that outgoing network traffic costs (for NA-NA, EU-Eu as an example) ~0.1$ per GiB.
I'm wondering if that also applies to downloading from cloud storage via the official library?

I intend to use cloud run to render videos created by users (via ffmpeg and pupeteer).
These videos can contain custom assets, like further videos, from my current understanding I would have to download all of these assets on each render call, even if only minimal changes where made. This could become extremely costly, especially since cloud run instances only offer 2gb memory at most.

Is my understanding correct, and is compute engine a viable alternative?

**Comment by ahmetb** [comment]
https://cloud.google.com/run/pricing is the place to look. No ingress charges for Cloud Run as far as I can tell. We are working on more flexible Cloud Run runtimes (cpu/memory) so stay tuned.

**Comment by Tobjoern** [comment]
Hm, well I looked at [https://cloud.google.com/run/pricing](https://cloud.google.com/run/pricing), and it refers to the the [premium pricing page](https://cloud.google.com/network-tiers/pricing#premium-pricing), which states that outgoing traffic consts ~0.1$ per GiB.
I don't quite understand what you mean by 'ingress chargs for cloud run', do you refer to the costs of booting the instances up (installing dependencies etc)?

**Comment by ahmetb** [comment]
Ingress and egress are usually well-established in hosting or cloud industry. 

- ingress costs: what your app downloads
- egress costs: traffic your app serves to users (upload)

Usually ingress isn’t charged, as most apps rely on serving traffic to users. Hope this helps.

**Comment by Tobjoern** [comment]
Thanks for the detailed answer, it really helps a lot!
Thinking about it, it would be quite ridiculous to charge for ingress costs, as event the most basic webserver has to download loads ob mb in dependencies.
