### ISSUE TITLE
Setting up test environment, to be available only for selected users.

### ISSUE THREAD

**Issue by Albertbol** [ahmetb/cloud-run-faq#80]
I was trying to find out how to set up test environment with Cloud Run to be available for selected users, for example i have front end application deployed to CloudRun, how is it possible to restrict permissions?
There is some information about logging in using curl and so on, but it all looks more like back-end authentication for specific routes, what about testing your app on mobile before releasing, google only mentions log in users sending requests with auth token headers and so on.
P.S Maybe there is another better solution to deploy to test environment and have a whitelisted IP addresses?

Thanks

**Comment by ahmetb** [comment]
To some extent https://cloud.google.com/run/docs/authenticating/end-users but with future integration with Cloud IAP it will get better.
