### ISSUE TITLE
Restart revision/service?

### ISSUE THREAD

**Issue by aaron-ikb** [ahmetb/cloud-run-faq#81]
Hi, some secrets are being loaded on startup, but I did not set the right permissions for the secret resources. I want to restart the revision/service/container so that it would try to get the secrets again.

App Engine Flexible has a way to "restart" it by deleting the instance. I wonder if Cloud Run has something similar, but I could not find it. Wondering if you guys have better luck figuring out how to do it.

**Comment by ahmetb** [comment]
There’s no instance management like that in Cloud Run. :) Deploy a new revision and switch traffic to the new one.
