### ISSUE TITLE
CDNs with Cloud Run

### ISSUE THREAD

**Issue by benmccann** [ahmetb/cloud-run-faq#84]
Hi, I'm not that familiar with Cloud Run, so I hope this isn't a dumb question. I see the README says:

> Since you **currently** can’t use [Cloud HTTP(S) Load Balancer][https-lb] with Cloud Run, you cannot use [Cloud CDN](https://cloud.google.com/cdn/). However, this is subject to change soon.

I'm wondering if this has already changed? I see the following doc which makes it look like it is possible:

https://cloud.google.com/solutions/integrating-https-load-balancing-with-istio-and-cloud-run-for-anthos-deployed-on-gke

If it's not possible yet, is there a ticket or article we could link to with more details about it potentially coming soon?

**Comment by ahmetb** [comment]
Thats for Cloud Run for Anthos. I will update it if changes.

**Comment by markalexander** [comment]
@ahmetb I believe both LB (and hence CDN) are in beta for Cloud Run FM now, see e.g. https://cloud.google.com/run/docs/using-gcp-services

**Comment by ahmetb** [comment]
Yeah I must make a comprehensive update.
