### ISSUE TITLE
32 MB request size limitation

### ISSUE THREAD

**Issue by somepablo** [ahmetb/cloud-run-faq#85]
Hi,

First or all, thanks for this useful GCR guide.

I'm currently looking for the best way to deploy microservices into GCE and thought GCR could be the best alternative for my use case, until I found this 32MB limitation.

Basically, what my microservices do is:

- Receive a video file between 5-100 MB
- Apply some filters / conversions
- Return a new video file between 5-100 MB

The conversion takes between 20 and 150 seconds.

At this moment, I have this service deployed on a GCE instance. However, I only receive about 50 requests / day, so I was looking for some way to save money an resources, and the scaling to zero feature of GCR attracted me.

Do you think GCR is a good alternative for my use case? If so, is there anything I can do to avoid the 32 MB limitation?

Thanks in advance.

**Comment by ahmetb** [comment]
Hi Pablo, I won’t be able to share the product roadmap with you unless you’re under NDA with Google Cloud. 

However, if you’re an active customer (let me know the company name) I am running office hours that you can book https://book.ahmet.im/ so I can explain some of the upcoming work wrt request timeouts and chunked large responses better.

**Comment by somepablo** [comment]
Thanks @ahmetb, just filled in the form.
