### ISSUE TITLE
Appropriate use cases for Cloud Run with CDN/LB

### ISSUE THREAD

**Issue by markalexander** [ahmetb/cloud-run-faq#87]
Hi,

Load balancer and CDN recently went into beta for Cloud Run and I'm wondering if I have the right use cases for it.

  1. Suppose I've got one service/endpoint in one region and I'd like to front it with a CDN so that my clients get a nice edge cache based on the headers I'm emitting.  I know the docs say I need to attach a load balancer first, then the CDN, but why?  Isn't Cloud Run already doing the load balancing part?  At least among containers.  Maybe the LB is more for routing to the nearest Cloud Run service by region, globally?  If so, isn't it just adding latency when I only use one region?  Any idea how much latency it will add and whether it's even notable?
  2. Suppose instead that I want to use some global distributed DB solution (like Spanner or Cockroach) and put Cloud Run services into a bunch of regions around the world that talk to the nearest DB endpoint.  Would load balancer then be what I use to route users to the right CR service in the closest region?  What happens if I use Cloud CDN then?  Will load balancer still be directing CDN passed through requests to the nearest Cloud Run instance?

Thanks for taking the time to read, and for maintaining this repo; it's been very helpful from when I started using Cloud Run a long time ago.

**Comment by ahmetb** [comment]
Good questions, and I'll be updating this repo today with the GCLB launch.

> 1. I know the docs say I need to attach a load balancer first, then the CDN, but why?

The "Google Cloud Load Balancer" and the load balancing Cloud Run does are different things. GCLB is a general purpose load balancer that supports many features like CDN, URL maps, IAP, DDoS protection, ...



> 1. If so, isn't it just adding latency when I only use one region?

Likely adds an unnoticeable latency. Most of our GCE VM infrastructure (GKE etc) uses this LB.



 

> 2. Would load balancer then be what I use to route users to the right CR service in the closest region?

Yes, users will be routed to the closest region that has a Cloud Run app deployed and added behind the LB.

> 2\. Will load balancer still be directing CDN passed through requests to the nearest Cloud Run instance?

Yes. Number of points of presence (PoPs) for CDN locations are far more greater than Cloud Run regions. So imagine you live in Berlin, you might hit a CDN edge pop location in Berlin, which proxies the request to the app deployed in the Frankfurt datacenter.

Hope this makes sense.

**Comment by markalexander** [comment]
Makes perfect sense, thank you. Especially the bit about why location
granularity of CDN PoPs vs regions matters.  Now I see why the combo works
for that case.

Looking forward to the updated docs and thanks for working on Cloud Run,
which I’m using for pretty much everything these days.
