### ISSUE TITLE
Question: "How to do multi-region with Cloud Run"

### ISSUE THREAD

**Issue by FGRibreau** [ahmetb/cloud-run-faq#9]
I'm pretty sure it's not currently possible but that's my goal : multi-region with Cloud Run, managed by Google infra + Google Cloud LB.

**Comment by ahmetb** [comment]
Are you looking to deploy an app once and have it be geo-distributed to all GCP regions supported and provisioned with a load-balancer that routes the traffic to the region closest to the user –––OR––– are you looking to do per-region deployments yourself and put them behind a Google Cloud LB that does global routing closest to the user?

**Comment by ahmetb** [comment]
Or is this mainly a "fault tolerance, because a region might go down" question?

To me it seems like doing multi-region is a solution to a problem. I'm curious what the problem is so I can curate the question better.

**Comment by FGRibreau** [comment]
> Are you looking to deploy an app once and have it be geo-distributed to all GCP regions supported and provisioned with a load-balancer that routes the traffic to the region closest to the user

That would be the best option indeed.

> To me it seems like doing multi-region is a solution to a problem. I'm curious what the problem is so I can curate the question better.

Yes it is, I maintain [Image-Charts](https://image-charts.com) and we must deliver <500ms latency over the world. We've got more than 1 million request per day from all over the world that we must answer as quickly as possible :)

**Comment by steren** [comment]
A solution for [Image-Charts](https://www.image-charts.com/) could be to put your Cloud Run service behind the [Firebase Hosting](https://firebase.google.com/docs/hosting/cloud-run) global CDN.

By setting the [right `cache-control` header](https://firebase.google.com/docs/hosting/manage-cache), the content served by your Cloud Run service will be cached by Firebase Hosting global CDN.

**Comment by manwithsteelnerves** [comment]
> A solution for [Image-Charts](https://www.image-charts.com/) could be to put your Cloud Run service behind the [Firebase Hosting](https://firebase.google.com/docs/hosting/cloud-run) global CDN.

Does Firebase global CDN take care of all security attacks? for ex: DDoS?

**Comment by ahmetb** [comment]
@manwithsteelnerves Please ask questions that aren’t directly about Cloud Run elsewhere such as Stackoverflow.com.
