### ISSUE TITLE
Does the number of allocated vCPUs affect network throughput?

### ISSUE THREAD

**Issue by bbzg** [ahmetb/cloud-run-faq#92]
Thanks for a great FAQ.

One question I have, that I have not found an answer for anywhere in the documentation, is: Does the number of allocated vCPUs affect network throughput?

Thanks

**Comment by ahmetb** [comment]
My guess would be "no". The throughput is not guaranteed on Cloud Run.

**Comment by bbzg** [comment]
Thanks. Feel free to close :)
