### ISSUE TITLE
Websockets | Cloud Run for Anthos

### ISSUE THREAD

**Issue by brianschardt** [ahmetb/cloud-run-faq#93]
Currently i moved over from Cloud Run Fully Managed to Cloud Run for Anthos to get the websocket functionality. However, when I try to connect a client to my api on Cloud Run for anthos I get the same error. 

Is there any special things I have to do to setup websockets? 
Or with my domain mapping?

**Comment by ahmetb** [comment]
You need to name your container port as h2c if you are using YAML. Otherwise use the http2 option in the gcloud cli.

**Comment by brianschardt** [comment]
Thanks so much for the response. So it does not support websockets with http1? My server only accepts http1 right now and I have just looked and it is super painful to get it to work with http2 at this moment.
Thanks for the help by the way.

**Comment by ahmetb** [comment]
H2c can also work with http1. Try it out. For more info, search: Knative websockets

**Comment by brianschardt** [comment]
When i use the the http2 option in the gcloud cli my server gives this 502 error for any request i make
```
unexpected EOF
```
When i build it without it, it works perfectly except websockets dont work. I thought it had something to de with my server not working with http2. I have been reading about Knative websockets all day. FAQ has helped me the most, so very much appreciate your help. 

Do you happen to know why i get the error I mentioned above?

**Comment by brianschardt** [comment]
Here is the github article I created: https://stackoverflow.com/questions/63912397/cloud-run-for-anthos-http2-unexpected-eof-error-gcp

im getting kind of desperate for a solution
