### ISSUE TITLE
Accessing external resource

### ISSUE THREAD

**Issue by deenar** [ahmetb/cloud-run-faq#94]
Hi

Thanks for the very useful resource. Can application on Cloud Run access external resources like s3 buckets or a RDS database on AWS?

**Comment by ahmetb** [comment]
Yeah, why wouldn't it be able to? :)

**Comment by deenar** [comment]
Thank you, I am new to all this. I have an app running on Heroku and trying to migrate to Google Cloud run. Will keep you posted on the progress

**Comment by ahmetb** [comment]
OK I'm on twitter, better to holler at me there :)
