### ISSUE TITLE
Graceful shutdown with SIGTERM

### ISSUE THREAD

**Issue by bodaniel** [ahmetb/cloud-run-faq#95]
Thanks for all the info!

While experimenting with graceful shutdowns I have noticed that SIGTERM is used when an instance is being stopped – not only SIGKILL as mentioned in the faq. I don’t know if there are any guarantees and how long time there is for graceful shutdowns, before SIGKILL is used.

Do you have more details regarding shutdown signals?

**Comment by ahmetb** [comment]
This is a relatively new properly so I'll update it when it's time.

**Comment by bodaniel** [comment]
Ok. Thanks!
